/**
 * Product  : Hiperium Project
 * Architect: Andres Solorzano.
 * Created  : 08-05-2009 - 23:30:00
 * 
 * The contents of this file are copyrighted by Andres Solorzano 
 * and it is protected by the license: "GPL V3." You can find a copy of this 
 * license at: http://www.hiperium.com/about/licence.html
 * 
 * Copyright 2014 Andres Solorzano. All rights reserved.
 * 
 */
package com.hiperium.messaging.exception;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * This is a subclass of RuntimeException class and implements the properties needed to
 * manage errors generated by the services.
 * 
 * @author Andres Solorzano.
 * 
 */
@XmlRootElement
public class InformationException extends Exception implements Serializable {

	/** The property serialVersionUID. */
	private static final long serialVersionUID = -2497389416820959668L;
	
	/**
	 * Default constructor. Used for Object Factory in SOAP Web Service Clients
	 */
	public InformationException() {
		// Nothing to do.
	}
	
	/**
	 * Class constructor.
	 * 
	 * @param message
	 *            the message to be send to the user.
	 */
	public InformationException(String message) {
		super(message);
	}
}
